server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /secret/ {
        return 404;
    }

    location ~ /\. {
        return 404;
    }
}

server {
    listen 18000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /secret/ {
        auth_basic "Restricted";
        auth_basic_user_file /usr/share/nginx/html/.htpasswd;
        try_files $uri $uri/ =404;
    }
}
